### ISSUE TITLE
应用市场选择分类后显示 %d个搜索结果

### ISSUE THREAD

**Issue by DevHaoZi** [litepress/litepress.cn#153]

**Comment by sunxiyuan** [comment]
是翻译的问题，woo 的单数形式和复数形式的原文语法不同。翻译平台已经支持了复数形式翻译修复了这个问题

**Comment by Yulinn233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
