### ISSUE TITLE
文档平台爬虫开发，用于录入codex.wordpress.org和developer.wordpress.org上的教程

### ISSUE THREAD

**Issue by sunxiyuan** [litepress/litepress.cn#17]

**Comment by star-studio975** [comment]
不建议从 codex.wordpress.org 获取文档，文档已经迁移到了 helphub，到时候这个平台会关闭

**Comment by sunxiyuan** [comment]
> 不建议从 codex.wordpress.org 获取文档，文档已经迁移到了 helphub，到时候这个平台会关闭

你说的 helphub 是 [https://cn.wordpress.org/support/](https://cn.wordpress.org/support/) 吗？

另外顺便问一下，你感觉翻译的时候夹杂在中文中的英语两侧有必要留空格吗？

比如说：

`你好，我是jack的跟班`

留空格后变成：

`你好，我是 jack 的跟班`

如果感觉有必要的话这种调整目前有能力应用到仓库中的所有翻译上。

然后基于对现存翻译进行批量更正的功能，我在想，是不是应该预留一种机制，标记一下哪些翻译是由机器和记忆库匹配出来的，这样将来可以在记忆库更完善或翻译算法更先进时进行批量的重新翻译。

目前记忆库的完整编辑工作是肯定做不完了，只能追求把其中两万条存在多条重复的翻译的词条人工编辑一下，其他的（还剩下十三万条不存在重复的翻译）只能以后发现问题后更正，然后再把更改规则这样应用到整个仓库上。

**Comment by star-studio975** [comment]
如果行的话这空格就尽量添加上吧。 另外可以参考一下 https://github.com/mzlogin/chinese-copywriting-guidelines/blob/Simplified/README.md------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月14日(星期六) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [litepress/litepress.cn] 文档平台爬虫开发，用于录入codex.wordpress.org和developer.wordpress.org上的教程 (#17)

**Comment by star-studio975** [comment]
中文版的 helphub 只翻译了几篇内容，剩余的都是草稿，要不等下给你添加个编辑权限方便获取------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月14日(星期六) 下午3:23
***@***.***&gt;;
***@***.***&gt;;&quot;Your ***@***.***&gt;;
主题:&nbsp;Re: [litepress/litepress.cn] 文档平台爬虫开发，用于录入codex.wordpress.org和developer.wordpress.org上的教程 (#17)

**Comment by sunxiyuan** [comment]
> 如果行的话这空格就尽量添加上吧。 另外可以参考一下 [https://github.com/mzlogin/chinese-copywriting-guidelines/blob/Simplified/README.md

兼容他这套规则是没问题的，可以针对性写一套处理算法。这套算法也可以在译者提交翻译时自动触发以对翻译格式化。

然后我在想，记忆库的编辑工作完成后，有没有必要把通过审核后的通用词汇的译文统一一下（统一指的的是把规则应用到整个仓库，替换掉其他翻译），比如说 add new 统一成新增。这其中会排除掉一些经常有歧义的词汇，比如说 m 和 min。

**Comment by sunxiyuan** [comment]
> 中文版的 helphub 只翻译了几篇内容，剩余的都是草稿，要不等下给你添加个编辑权限方便获取

文档的获取只能通过爬虫了，因为即便我可以获取 cn.wordpress.org 的编辑权限也获取不到 developer.wordpress.org 的权限。

不过如果能有权限看一看 wordpress.org 的工作机制的话还是会帮助少走一些弯路的，我的登录名：sunxiyuan

**Comment by star-studio975** [comment]
这样是可以，但是会破坏掉一些翻译:比如 add new，有时候我们会根据上下文进行翻译，比如上下文中提示 page 我们就会翻译成新建页面或者添加页面------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月14日(星期六) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [litepress/litepress.cn] 文档平台爬虫开发，用于录入codex.wordpress.org和developer.wordpress.org上的教程 (#17)

**Comment by star-studio975** [comment]
可以了

https://cn.wordpress.org/support/wp-admin/

**Comment by sunxiyuan** [comment]
> 可以了 https://cn.wordpress.org/support/wp-admin/

现在前面提到的对翻译格式化的功能已经实现了，而且也已经批量应用到了仓库上，格式化除了加空格外还包括对常见名词调用正确大小写。

不过有个问题得咨询一下你，比如说下面的语句：
```
根据需要选择 %1$s 用户类型 %2$s。如果您想要为任何拥有 Google 帐户的用户启用 Google 社交登录，请选择外部选项！
```
在上面的语句中，是否需要为%1$s和%2$s两侧加空格？加了的话是否会造成问题？

**Comment by star-studio975** [comment]
我觉得最好还是加上空格，因为这些占位符包含的信息一般都是英文或者数字之类的，我参考了一下繁体中文翻译，发现他们也是留空格的，没有多大影响

**Comment by star-studio975** [comment]
这个也可以参考一下

https://wiki.ubuntu.org.cn/Ubuntu_%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%B0%8F%E7%BB%84%E5%B7%A5%E4%BD%9C%E6%8C%87%E5%8D%97
