### ISSUE TITLE
在头像不存在使用默认头像时，如何判定？

### ISSUE THREAD

**Issue by OhYee** [litepress/litepress.cn#178]
如在使用默认头像时，有不同的状态码或是响应头部
试了下，好像成功请求和默认头像没有区别

**Comment by sunxiyuan** [comment]
我没明白你说的 “如在使用默认头像时，有不同的状态码或是响应头部” 是什么意思。

如果你是想问如何在未匹配到头像时直接返回 404 状态码而不是默认图的话，可以拼接 d 参数，值为 404，比如：
https://cravatar.cn/avatar/4c2a1e88031a2ea87817acfa2a11e059?s=400&r=G&d=404

**Comment by OhYee** [comment]
感谢，就是需要这种效果
