### ISSUE TITLE
【MySQL8 适配】Query Monitor插件无法使用

### ISSUE THREAD

**Issue by sunxiyuan** [litepress/litepress.cn#22]

**Comment by DevHaoZi** [comment]
测试了PHP8.0.3以及MariaDB10.5和WP5.8-RC4，工作正常

**Comment by DevHaoZi** [comment]
顺利在旧平台完成全部翻译核对。

**Comment by sunxiyuan** [comment]
> 测试了PHP8.0.3以及MariaDB10.5和WP5.8-RC4，工作正常

litepress.cn是MySQL 8

**Comment by DevHaoZi** [comment]
> > 测试了PHP8.0.3以及MariaDB10.5和WP5.8-RC4，工作正常
> 
> litepress.cn是MySQL 8

那你的标题就写错了，应该是MySQL8。
